version: "3.8"

services:
  web:
    build: .
    container_name: myjobtracker-web
    ports:
      - "5100:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgres://postgres:postgres@db:5432/myjobtracker
      SESSION_SECRET: your_session_secret_here
      UPLOAD_DIR: /app/public/uploads
      COOKIE_DOMAIN: ""
    volumes:
      - uploads:/app/public/uploads
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: myjobtracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myjobtracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  uploads:
  db_data: